name: fpm-deployment

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: {compiler: gcc, version: 13, flags: ['-cpp -O3']}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1

      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip install --upgrade -r config/requirements.txt

      - uses: fortran-lang/setup-fortran@main
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Setup Fortran Package Manager
        uses: fortran-lang/setup-fpm@v5
        with:
          fpm-version: 'v0.10.0'

      - run: |
          python config/fypp_deployment.py --deploy_stdlib_fpm
          fpm test --flag "${{ join(matrix.toolchain.flags, ' ') }}"

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm` branch.
    # might no longer be needed
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm
          FOLDER: stdlib-fpm